# Generated by Django 5.1.3 on 2024-12-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
